### PR TITLE
version bump to 0.44.05-r1

### PR DESCRIPTION
**Pull request by albron**
Compiled fine on my system. Also launches without problems.

### CODE REVIEW

**Comment by wookietreiber** [comment]
I had already pushed it to AUR, not here, though.

**Comment by albron** [comment]
I now notice. Although this would be the stable release for 0.44.05-r1, not the alpha.

**Comment by wookietreiber** [comment]
I didn't notice the **r1**, my bad. I reopened and will take care of this in the evening (currently at work).

**Comment by wookietreiber** [comment]
BTW, if you have time until then, please rebase on master.

**Comment by albron** [comment]
Not sure if this is what you asked for, I removed the trivial conflicts. Let me know.

**Comment by wookietreiber** [comment]
I've meant rebase, not merge. No worries, though, I cherry-pick'ed your commit on top of master.

**Pull request closed without merging**
